export const SUBCATEGORIAS_MAP: Record<string, string[]> = {
  Hardware: [
    "Processadores",
    "Placas de Vídeo",
    "Memórias RAM",
    "Armazenamento",
    "SSDs",
    "Placas-Mãe",
    "Fontes de Alimentação",
    "Gabinetes",
    "Coolers e Sistemas de Refrigeração",
  ],
  Perifericos: [
    "Monitores",
    "Mouses",
    "Teclados",
    "Headsets",
    "Webcams",
    "Impressoras",
    "Scanners",
    "Diversos",
  ],
  Smartphones: ["Android", "iOS"],
  Tablets: ["Android", "iOS"],
  Notebooks: ["Ultrabooks", "Gaming", "2 em 1"],
  Desktops: ["All-in-One", "Gaming", "Workstations"],
  Acessórios: [
    "Carregadores",
    "Capas e Cases",
    "Películas de Proteção",
    "Fones de Ouvido",
    "Cabos e Adaptadores",
    "Suportes e Docking Stations",
    "Outros Acessórios",
  ],
  Smartwatches: [
    "Android",
    "iOS",
    "Híbridos",
    "Acessórios",
    "Smartwatches Básicos",
    "Smartwatches Intermediários",
    "Smartwatches Avançados",
  ],
  Fones: [
    "Intra-auriculares",
    "Supra-auriculares",
    "Circum-auriculares",
    "Sem Fio",
    "Com Fio",
    "Acessórios",
  ],
  Câmeras: [
    "DSLR",
    "Mirrorless",
    "Compactas",
    "Acessórios",
    "Lentes",
    "Tripés",
    "Iluminação",
    "Outros Acessórios",
  ],
  Televisores: [
    "LED",
    "OLED",
    "QLED",
    "4K",
    "8K",
    "Smart TVs",
    "Acessórios",
    "Suportes",
    "Cabos HDMI",
    "Outros Acessórios",
  ],
  Consoles: ["PlayStation", "Xbox", "Nintendo", "Acessórios"],
  Drones: [
    "Drones para Iniciantes",
    "Drones Intermediários",
    "Drones Avançados",
    "Acessórios",
    "Baterias",
    "Hélices",
    "Câmeras",
    "Outros Acessórios",
  ],
  Roteadores: [
    "Roteadores Domésticos",
    "Roteadores para Empresas",
    "Modems",
    "Acessórios",
    "Antenas",
    "Cables",
    "Outros Acessórios",
  ],
};
